name: prerelease NuGet

on: 
  push:
    branches:
      - prerelease

jobs:
  build:
    runs-on: ubuntu-latest
    # also works with windows-latest and macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool
      shell: pwsh  
    - name: Determine Version
      run: dotnet gitversion /updateprojectfiles 
      shell: pwsh
    - name: Build with dotnet
      run: dotnet build --configuration Release
      shell: pwsh
    - name: dotnet pack
      run: |
        $t = Get-Date -Format "yyyyMMdd-HHmmss"
        dotnet pack -c Release --output ${{github.workspace}} --version-suffix prerelease-$t
      shell: pwsh
    - name: Publish NuGet Package
      run: dotnet nuget push "${{github.workspace}}/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      shell: pwsh
