name: prerelease NuGet

on: 
  push:
    branches:
      - prerelease

jobs:
  build:
    runs-on: ubuntu-latest
    # also works with windows-latest and macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool
      shell: pwsh  
    - name: Determine Version
      run: dotnet gitversion /updateprojectfiles 
      shell: pwsh
    - name: Build with dotnet
      run: |
            dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
            dotnet pack
      shell: pwsh
    - name: List Artifacts
      run: ls **/*.nupkg
      shell: pwsh
    - name: Publish NuGet Package
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      shell: pwsh
